\version "2.24.3"
\language "english"
\score
{
    % OPEN_BRACKETS:
    \new Score
    <<
        % OPEN_BRACKETS:
        \new Staff
        {
            f,,4
            f,,4
            f,,4
            e,,4
            f,,4
            e,,4
            e,,4
            e,,4
            e,,4
            e,,4
            e,,4
            e,,4
            e,,4
            e,,4
            f,,4
            f,,4
            e,,4
            g,,4
            a,,4
            a,,4
            a,,4
            a,,4
            g,,4
            g,,4
            f,,4
            e,,4
            e,,4
            e,,4
            e,,4
            e,,4
            e,,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            c,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            d,4
            c,4
            e,4
            e,4
            e,4
            e,4
            e,4
            e,4
            e,4
            e,4
            e,4
            e,4
            e,4
            e,4
            e,4
            e,4
            e,4
            e,4
            e,4
            e,4
            f,4
            f,4
            g,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            g,4
            f,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            a,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            f,4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
            c4
        % CLOSE_BRACKETS:
        }
    % CLOSE_BRACKETS:
    >>
}
