name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Homebrew dependencies
        uses: actions/cache@v3
        with:
          path: /opt/homebrew
          key: ${{ runner.os }}-brew-cache
          restore-keys: |
            ${{ runner.os }}-brew-cache

      - name: Install Homebrew packages
        shell: bash
        run: |
          brew install ffmpeg
          brew install lilypond

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python environment
        shell: bash
        run: |
          if [ -d "./venv" ]; then
            rm -rf ./venv
          fi
          python3.11 -m venv venv
          source ./venv/bin/activate

      - name: Install Python dependencies
        shell: bash
        run: |
          source ./venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        shell: bash
        run: |
          source ./venv/bin/activate
          make test

