name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Homebrew dependencies
        uses: actions/cache@v3
        with:
          path: /usr/local/Homebrew  # or /opt/homebrew for Apple Silicon Macs
          key: ${{ runner.os }}-brew-${{ hashFiles('Brewfile') }}
          restore-keys: |
            ${{ runner.os }}-brew-

      - name: Install Homebrew packages
        shell: bash
        run: |
          brew bundle --file=Brewfile || brew bundle dump --file=Brewfile

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Homebrew dependencies
        shell: bash
        run: |
          brew install ffmpeg
          brew install lilypond

      - name: Set up Python environment and install dependencies
        shell: bash
        run: |
          if [ -d "./venv" ]; then
            rm -rf ./venv
          fi
          python3.11 -m venv venv
          source ./venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        shell: bash
        run: |
          source ./venv/bin/activate
          make test

  deploy:
    runs-on: macos-14
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Main
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          echo "All tests passed, deploying to main"
          # Deployment steps here

      - name: Push to main
        if: github.ref != 'refs/heads/main'
        shell: bash
        run: |
          git checkout main
          git merge ${{ github.ref }}
          git push origin main

