name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Homebrew dependencies
        shell: bash
        run: |
          brew install ffmpeg
          brew install lilypond

      - name: Set up Python environment and install dependencies
        shell: bash
        run: |
          if [ -d "./venv" ]; then
            rm -rf ./venv
          fi
          python3.11 -m venv venv
          source ./venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        shell: bash
        run: |
          source ./venv/bin/activate
          make test

  deploy:
    runs-on: macos-14
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Main
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          echo "All tests passed, deploying to main"
          # Deployment steps here

      - name: Push to main
        if: github.ref != 'refs/heads/main'
        shell: bash
        run: |
          git checkout main
          git merge ${{ github.ref }}
          git push origin main

